export const mockRecipes = [
  {
    id: 652332,
    image: "https://img.spoonacular.com/recipes/652332-556x370.jpg",
    imageType: "jpg",
    title: "Monastery soup",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "https://www.foodista.com/recipe/Y67R5WMP/monastery-soup",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 7,
    healthScore: 39.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 156.78,
    extendedIngredients: [
      {
        id: 11352,
        aisle: "Produce",
        image: "potatoes-yukon-gold.png",
        consistency: "SOLID",
        name: "potatoes",
        nameClean: "potatoes",
        original: "2 large potatoes, chopped into 1cm cubes",
        originalName: "potatoes, chopped into 1cm cubes",
        amount: 2.0,
        unit: "large",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 large onion, chopped",
        originalName: "onion, chopped",
        amount: 1.0,
        unit: "large",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "large",
            unitLong: "large",
          },
          metric: {
            amount: 1.0,
            unitShort: "large",
            unitLong: "large",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "2 cloves garlic, chopped",
        originalName: "garlic, chopped",
        amount: 2.0,
        unit: "cloves",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "cloves",
            unitLong: "cloves",
          },
          metric: {
            amount: 2.0,
            unitShort: "cloves",
            unitLong: "cloves",
          },
        },
      },
      {
        id: 4584,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vegetable-oil.jpg",
        consistency: "LIQUID",
        name: "sunflower oil",
        nameClean: "sunflower oil",
        original: "2 Tbs sunflower oil",
        originalName: "sunflower oil",
        amount: 2.0,
        unit: "Tbs",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "SOLID",
        name: "carrots",
        nameClean: "carrots",
        original: "2 large carrots, peeled and chopped",
        originalName: "carrots, peeled and chopped",
        amount: 2.0,
        unit: "large",
        meta: ["peeled", "chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 11246,
        aisle: "Produce",
        image: "leeks.jpg",
        consistency: "SOLID",
        name: "leek",
        nameClean: "leek",
        original: "1 leek, washed thoroughly, sliced",
        originalName: "leek, washed thoroughly, sliced",
        amount: 1.0,
        unit: "",
        meta: ["washed", "sliced"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11143,
        aisle: "Produce",
        image: "celery.jpg",
        consistency: "SOLID",
        name: "celery",
        nameClean: "celery",
        original: "2 sticks celery, sliced",
        originalName: "celery, sliced",
        amount: 2.0,
        unit: "sticks",
        meta: ["sliced"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "sticks",
            unitLong: "sticks",
          },
          metric: {
            amount: 2.0,
            unitShort: "sticks",
            unitLong: "sticks",
          },
        },
      },
      {
        id: 16053,
        aisle: "Pasta and Rice",
        image: "broad-beans.jpg",
        consistency: "SOLID",
        name: "broad beans",
        nameClean: "broad beans",
        original: "100g broad beans",
        originalName: "broad beans",
        amount: 100.0,
        unit: "g",
        meta: [],
        measures: {
          us: {
            amount: 3.527,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 100.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "vegetable stock",
        nameClean: "vegetable stock",
        original: "1 l vegetable stock",
        originalName: "vegetable stock",
        amount: 1.0,
        unit: "l",
        meta: [],
        measures: {
          us: {
            amount: 1.046,
            unitShort: "qt",
            unitLong: "quarts",
          },
          metric: {
            amount: 1.0,
            unitShort: "l",
            unitLong: "liter",
          },
        },
      },
      {
        id: 10511297,
        aisle: "Produce",
        image: "parsley.jpg",
        consistency: "SOLID",
        name: "parsley",
        nameClean: "parsley",
        original: "Handful fresh parsley, chopped",
        originalName: "fresh parsley, chopped",
        amount: 1.0,
        unit: "Handful",
        meta: ["fresh", "chopped"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Handful",
            unitLong: "Handful",
          },
          metric: {
            amount: 1.0,
            unitShort: "Handful",
            unitLong: "Handful",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "Salt and pepper",
        originalName: "Salt and pepper",
        amount: 4.0,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    summary:
      'Monastery soup is a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> recipe with 4 servings. One serving contains <b>293 calories</b>, <b>7g of protein</b>, and <b>8g of fat</b>. For <b>$1.57 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. 7 people were glad they tried this recipe. It works best as a hor d\'oeuvre, and is done in approximately <b>45 minutes</b>. It will be a hit at your <b>Autumn</b> event. This recipe from Foodista requires parsley, carrots, broad beans, and vegetable stock. With a spoonacular <b>score of 89%</b>, this dish is super. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/monastery-soup-1412001">Monastery soup</a>, <a href="https://spoonacular.com/recipes/a-quick-and-easy-soup-miso-soup-with-soba-noodles-or-mung-bean-31003">A Quick And Easy Soup {miso Soup With Soba Noodles Or Mung Bean</a>, and <a href="https://spoonacular.com/recipes/pea-soup-with-lettuce-and-mint-aka-clean-out-the-fridge-soup-569347">Pea soup with lettuce and mint (aka: clean out the fridge soup!)</a>.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "soup",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: ["fall", "winter"],
    instructions:
      "1. Heat the oil in a large pan, add the potato, onion and garlic and saut, covered, for 10 minutes.\n2. Add the carrots, leek  and celery and saut for 5 minutes.\n3. Add broad beans and vegetable stock. Cover and simmer gently for 10 minutes, until the potatoes and broad beans are soft.\n4. Add parsley and salt  and pepper if needed.\nServe with crusty bread.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Heat the oil in a large pan, add the potato, onion and garlic and saut, covered, for 10 minutes.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "https://spoonacular.com/cdn/equipment_100x100/pan.png",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Add the carrots, leek  and celery and saut for 5 minutes.",
            ingredients: [
              {
                id: 11124,
                name: "carrot",
                localizedName: "carrot",
                image: "sliced-carrot.png",
              },
              {
                id: 11143,
                name: "celery",
                localizedName: "celery",
                image: "celery.jpg",
              },
              {
                id: 11246,
                name: "leek",
                localizedName: "leek",
                image: "leeks.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Add broad beans and vegetable stock. Cover and simmer gently for 10 minutes, until the potatoes and broad beans are soft.",
            ingredients: [
              {
                id: 6615,
                name: "vegetable stock",
                localizedName: "vegetable stock",
                image: "chicken-broth.png",
              },
              {
                id: 16053,
                name: "fava beans",
                localizedName: "fava beans",
                image: "broad-beans.jpg",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Add parsley and salt  and pepper if needed.",
            ingredients: [
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
              {
                id: 1002030,
                name: "pepper",
                localizedName: "pepper",
                image: "pepper.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Serve with crusty bread.",
            ingredients: [
              {
                id: 10018029,
                name: "crusty bread",
                localizedName: "crusty bread",
                image: "crusty-bread.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 88.15331268310547,
    spoonacularSourceUrl: "https://spoonacular.com/monastery-soup-652332",
  },
  {
    id: 640575,
    image: "https://img.spoonacular.com/recipes/640575-556x370.png",
    imageType: "png",
    title: "Creamed Sweet Onion with Butter Basil Biscuits",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/MVQ4LBNM/creamed-sweet-onion-with-butter-basil-biscuits",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 16,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 2,
    healthScore: 1.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 133.86,
    extendedIngredients: [
      {
        id: 11294,
        aisle: "Produce",
        image: "sweet-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 Sweet Onion, halved and sliced",
        originalName: "Sweet Onion, halved and sliced",
        amount: 1.0,
        unit: "",
        meta: ["sweet", "halved", "sliced"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10123,
        aisle: "Meat",
        image: "raw-bacon.png",
        consistency: "SOLID",
        name: "bacon",
        nameClean: "bacon",
        original: "4 strips of bacon",
        originalName: "bacon",
        amount: 4.0,
        unit: "strips",
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "strips",
            unitLong: "strips",
          },
          metric: {
            amount: 4.0,
            unitShort: "strips",
            unitLong: "strips",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1 tbsp olive oil",
        originalName: "olive oil",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 1012049,
        aisle: "Produce",
        image: "thyme.jpg",
        consistency: "SOLID",
        name: "thyme",
        nameClean: "thyme",
        original: "2 sprigs of fresh thyme",
        originalName: "fresh thyme",
        amount: 2.0,
        unit: "sprigs",
        meta: ["fresh"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "sprigs",
            unitLong: "sprigs",
          },
          metric: {
            amount: 2.0,
            unitShort: "sprigs",
            unitLong: "sprigs",
          },
        },
      },
      {
        id: 6194,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "chicken broth",
        nameClean: "chicken broth",
        original: "1 cup chicken broth",
        originalName: "chicken broth",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 235.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14106,
        aisle: "Alcoholic Beverages",
        image: "white-wine.jpg",
        consistency: "LIQUID",
        name: "white wine",
        nameClean: "white wine",
        original: "¼ cup white wine",
        originalName: "white wine",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 60.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "1 tbsp of butter",
        originalName: "butter",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "flour",
        original: "1 tbsp flour",
        originalName: "flour",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 1049,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "SOLID",
        name: "half and half",
        nameClean: "half and half",
        original: "¼ cup half and half",
        originalName: "half and half",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 60.5,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "Pinch of nutmeg",
        originalName: "Pinch of nutmeg",
        amount: 1.0,
        unit: "pinch",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "pinch",
            unitLong: "pinch",
          },
          metric: {
            amount: 1.0,
            unitShort: "pinch",
            unitLong: "pinch",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "Salt and pepper to taste",
        originalName: "Salt and pepper to taste",
        amount: 4.0,
        unit: "servings",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "all purpose flour",
        nameClean: "all purpose flour",
        original: "1 ¾ all purpose flour",
        originalName: "all purpose flour",
        amount: 1.75,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.75,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.75,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 18369,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "baking powder",
        nameClean: "baking powder",
        original: "1 tbsp baking powder",
        originalName: "baking powder",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "salt",
        original: "½ tsp salt",
        originalName: "salt",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1145,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "6 tbsp unsalted butter, cubed",
        originalName: "unsalted butter, cubed",
        amount: 6.0,
        unit: "tbsp",
        meta: ["unsalted", "cubed"],
        measures: {
          us: {
            amount: 6.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 6.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 2044,
        aisle: "Produce",
        image: "fresh-basil.jpg",
        consistency: "SOLID",
        name: "basil",
        nameClean: "basil",
        original: "¼ cup fresh basil, chiffonade",
        originalName: "fresh basil, chiffonade",
        amount: 0.25,
        unit: "cup",
        meta: ["fresh"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 6.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1049,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "SOLID",
        name: "half and half",
        nameClean: "half and half",
        original: "¾ half and half",
        originalName: "half and half",
        amount: 0.75,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 0.75,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 0.75,
            unitShort: "",
            unitLong: "",
          },
        },
      },
    ],
    summary:
      'Creamed Sweet Onion with Butter Basil Biscuits might be just the hor d\'oeuvre you are searching for. This recipe serves 4 and costs $1.34 per serving. One serving contains <b>375 calories</b>, <b>5g of protein</b>, and <b>34g of fat</b>. This recipe from Foodista requires all purpose flour, bacon, white wine, and butter. 2 people found this recipe to be delicious and satisfying. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. With a spoonacular <b>score of 22%</b>, this dish is not so amazing. Try <a href="https://spoonacular.com/recipes/creamed-sweet-onion-with-butter-basil-biscuits-1369487">Creamed Sweet Onion with Butter Basil Biscuits</a>, <a href="https://spoonacular.com/recipes/warm-octopus-and-sweet-onion-salad-with-fresh-basil-and-lemon-vinaigrette-328022">Warm Octopus and Sweet Onion Salad with Fresh Basil and Lemon Vinaigrette</a>, and <a href="https://spoonacular.com/recipes/sweet-potato-biscuits-with-honey-butter-586112">Sweet Potato Biscuits with Honey Butter</a> for similar recipes.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: [],
    occasions: [],
    instructions:
      "Preheat oven to 450\nIn a heavy bottom pot fry bacon over medium heat until crispy.\nRemove from pot and leave to cool on a plate lined with paper towel.\nSpoon off the bacon grease leaving 2 tbsp worth in the pot.\nAdd the olive oil to keep the fat from burning and toss in the onions.\nSautee for 2-3 minutes.\nPour in broth and add the two sprigs of thyme.\nBring the mixture up to a boil and reduce heat and leave to simmer covered for 5 minutes.\nOnce onions are tender add white wine and leave to boil until the liquid is reduced by half.  About 10 minutes.\nIn a small saucepan melt butter over medium heat.\nWhisk in flour until it forms a paste.\nSlowly whisk in half and half until combined.  Remove from heat and add to the onion mixture. Stir until thickened.\nRemove from heat and set aside.\nSpoon into 4 ramenkins and top each with an uncooked biscuit.\nPlace in the oven and cook for 15 minutes until the biscuits are golden brown.\nRemove from the oven and leave to cool for ten minutes before serving.\nFOR THE BISCUITS\nSift together flour, baking powder, and salt into a large mixing bowl.\nAdd butter and basil.\nCut the butter into the dry mixture using a pastry blender or two knives until it resembles a coarse meal.\nMake a well in the center of the mixture and pour in the half and half.\nStir until the dough comes together.\nTurn dough onto a well-floured surface.\nFlatten dough to  an inch thickness.\nUsing a 2  biscuit cutter cut out 12 biscuits.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 450",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "In a heavy bottom pot fry bacon over medium heat until crispy.",
            ingredients: [
              {
                id: 10123,
                name: "bacon",
                localizedName: "bacon",
                image:
                  "https://spoonacular.com/cdn/ingredients_100x100/raw-bacon.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Remove from pot and leave to cool on a plate lined with paper towel.",
            ingredients: [],
            equipment: [
              {
                id: 405895,
                name: "paper towels",
                localizedName: "paper towels",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/paper-towels.jpg",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Spoon off the bacon grease leaving 2 tbsp worth in the pot.",
            ingredients: [
              {
                id: 4609,
                name: "bacon drippings",
                localizedName: "bacon drippings",
                image: "raw-bacon.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
              },
            ],
          },
          {
            number: 5,
            step: "Add the olive oil to keep the fat from burning and toss in the onions.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: "Sautee for 2-3 minutes.",
            ingredients: [],
            equipment: [],
            length: {
              number: 3,
              unit: "minutes",
            },
          },
          {
            number: 7,
            step: "Pour in broth and add the two sprigs of thyme.",
            ingredients: [
              {
                id: 1006615,
                name: "broth",
                localizedName: "broth",
                image: "chicken-broth.png",
              },
              {
                id: 2049,
                name: "thyme",
                localizedName: "thyme",
                image: "thyme.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Bring the mixture up to a boil and reduce heat and leave to simmer covered for 5 minutes.",
            ingredients: [],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 9,
            step: "Once onions are tender add white wine and leave to boil until the liquid is reduced by half.  About 10 minutes.",
            ingredients: [
              {
                id: 14106,
                name: "white wine",
                localizedName: "white wine",
                image: "white-wine.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 10,
            step: "In a small saucepan melt butter over medium heat.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/sauce-pan.jpg",
              },
            ],
          },
          {
            number: 11,
            step: "Whisk in flour until it forms a paste.",
            ingredients: [
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 12,
            step: "Slowly whisk in half and half until combined.",
            ingredients: [
              {
                id: 1049,
                name: "half and half",
                localizedName: "half and half",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 13,
            step: "Remove from heat and add to the onion mixture. Stir until thickened.",
            ingredients: [
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 14,
            step: "Remove from heat and set aside.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 15,
            step: "Spoon into 4 ramenkins and top each with an uncooked biscuit.",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 16,
            step: "Place in the oven and cook for 15 minutes until the biscuits are golden brown.",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              },
            ],
            length: {
              number: 15,
              unit: "minutes",
            },
          },
          {
            number: 17,
            step: "Remove from the oven and leave to cool for ten minutes before serving.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 18,
            step: "FOR THE BISCUITS",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 19,
            step: "Sift together flour, baking powder, and salt into a large mixing bowl.",
            ingredients: [
              {
                id: 18369,
                name: "baking powder",
                localizedName: "baking powder",
                image: "white-powder.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 405907,
                name: "mixing bowl",
                localizedName: "mixing bowl",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/mixing-bowl.jpg",
              },
            ],
          },
          {
            number: 20,
            step: "Add butter and basil.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 2044,
                name: "basil",
                localizedName: "basil",
                image: "basil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 21,
            step: "Cut the butter into the dry mixture using a pastry blender or two knives until it resembles a coarse meal.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/blender.png",
              },
            ],
          },
          {
            number: 22,
            step: "Make a well in the center of the mixture and pour in the half and half.",
            ingredients: [
              {
                id: 1049,
                name: "half and half",
                localizedName: "half and half",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 23,
            step: "Stir until the dough comes together.",
            ingredients: [
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 24,
            step: "Turn dough onto a well-floured surface.",
            ingredients: [
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 25,
            step: "Flatten dough to  an inch thickness.",
            ingredients: [
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 26,
            step: "Using a 2  biscuit cutter cut out 12 biscuits.",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 28.46582794189453,
    spoonacularSourceUrl:
      "https://spoonacular.com/creamed-sweet-onion-with-butter-basil-biscuits-640575",
  },
];

// For extended Ingredients use "original" tag? (example: "        original: "1 onion, chopped",
// ")
