export const mockRecipes = [
  {
    id: 652332,
    image: "https://img.spoonacular.com/recipes/652332-556x370.jpg",
    imageType: "jpg",
    title: "Monastery soup",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "https://www.foodista.com/recipe/Y67R5WMP/monastery-soup",
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 8,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 7,
    healthScore: 39.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 156.78,
    extendedIngredients: [
      {
        id: 11352,
        aisle: "Produce",
        image: "potatoes-yukon-gold.png",
        consistency: "SOLID",
        name: "potatoes",
        nameClean: "potatoes",
        original: "2 large potatoes, chopped into 1cm cubes",
        originalName: "potatoes, chopped into 1cm cubes",
        amount: 2.0,
        unit: "large",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 large onion, chopped",
        originalName: "onion, chopped",
        amount: 1.0,
        unit: "large",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "large",
            unitLong: "large",
          },
          metric: {
            amount: 1.0,
            unitShort: "large",
            unitLong: "large",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "2 cloves garlic, chopped",
        originalName: "garlic, chopped",
        amount: 2.0,
        unit: "cloves",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "cloves",
            unitLong: "cloves",
          },
          metric: {
            amount: 2.0,
            unitShort: "cloves",
            unitLong: "cloves",
          },
        },
      },
      {
        id: 4584,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vegetable-oil.jpg",
        consistency: "LIQUID",
        name: "sunflower oil",
        nameClean: "sunflower oil",
        original: "2 Tbs sunflower oil",
        originalName: "sunflower oil",
        amount: 2.0,
        unit: "Tbs",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "SOLID",
        name: "carrots",
        nameClean: "carrots",
        original: "2 large carrots, peeled and chopped",
        originalName: "carrots, peeled and chopped",
        amount: 2.0,
        unit: "large",
        meta: ["peeled", "chopped"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 2.0,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 11246,
        aisle: "Produce",
        image: "leeks.jpg",
        consistency: "SOLID",
        name: "leek",
        nameClean: "leek",
        original: "1 leek, washed thoroughly, sliced",
        originalName: "leek, washed thoroughly, sliced",
        amount: 1.0,
        unit: "",
        meta: ["washed", "sliced"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11143,
        aisle: "Produce",
        image: "celery.jpg",
        consistency: "SOLID",
        name: "celery",
        nameClean: "celery",
        original: "2 sticks celery, sliced",
        originalName: "celery, sliced",
        amount: 2.0,
        unit: "sticks",
        meta: ["sliced"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "sticks",
            unitLong: "sticks",
          },
          metric: {
            amount: 2.0,
            unitShort: "sticks",
            unitLong: "sticks",
          },
        },
      },
      {
        id: 16053,
        aisle: "Pasta and Rice",
        image: "broad-beans.jpg",
        consistency: "SOLID",
        name: "broad beans",
        nameClean: "broad beans",
        original: "100g broad beans",
        originalName: "broad beans",
        amount: 100.0,
        unit: "g",
        meta: [],
        measures: {
          us: {
            amount: 3.527,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 100.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 6615,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "vegetable stock",
        nameClean: "vegetable stock",
        original: "1 l vegetable stock",
        originalName: "vegetable stock",
        amount: 1.0,
        unit: "l",
        meta: [],
        measures: {
          us: {
            amount: 1.046,
            unitShort: "qt",
            unitLong: "quarts",
          },
          metric: {
            amount: 1.0,
            unitShort: "l",
            unitLong: "liter",
          },
        },
      },
      {
        id: 10511297,
        aisle: "Produce",
        image: "parsley.jpg",
        consistency: "SOLID",
        name: "parsley",
        nameClean: "parsley",
        original: "Handful fresh parsley, chopped",
        originalName: "fresh parsley, chopped",
        amount: 1.0,
        unit: "Handful",
        meta: ["fresh", "chopped"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Handful",
            unitLong: "Handful",
          },
          metric: {
            amount: 1.0,
            unitShort: "Handful",
            unitLong: "Handful",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "Salt and pepper",
        originalName: "Salt and pepper",
        amount: 4.0,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    summary:
      'Monastery soup is a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> recipe with 4 servings. One serving contains <b>293 calories</b>, <b>7g of protein</b>, and <b>8g of fat</b>. For <b>$1.57 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. 7 people were glad they tried this recipe. It works best as a hor d\'oeuvre, and is done in approximately <b>45 minutes</b>. It will be a hit at your <b>Autumn</b> event. This recipe from Foodista requires parsley, carrots, broad beans, and vegetable stock. With a spoonacular <b>score of 89%</b>, this dish is super. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/monastery-soup-1412001">Monastery soup</a>, <a href="https://spoonacular.com/recipes/a-quick-and-easy-soup-miso-soup-with-soba-noodles-or-mung-bean-31003">A Quick And Easy Soup {miso Soup With Soba Noodles Or Mung Bean</a>, and <a href="https://spoonacular.com/recipes/pea-soup-with-lettuce-and-mint-aka-clean-out-the-fridge-soup-569347">Pea soup with lettuce and mint (aka: clean out the fridge soup!)</a>.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "soup",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: ["fall", "winter"],
    instructions:
      "1. Heat the oil in a large pan, add the potato, onion and garlic and saut, covered, for 10 minutes.\n2. Add the carrots, leek  and celery and saut for 5 minutes.\n3. Add broad beans and vegetable stock. Cover and simmer gently for 10 minutes, until the potatoes and broad beans are soft.\n4. Add parsley and salt  and pepper if needed.\nServe with crusty bread.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Heat the oil in a large pan, add the potato, onion and garlic and saut, covered, for 10 minutes.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "https://spoonacular.com/cdn/equipment_100x100/pan.png",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Add the carrots, leek  and celery and saut for 5 minutes.",
            ingredients: [
              {
                id: 11124,
                name: "carrot",
                localizedName: "carrot",
                image: "sliced-carrot.png",
              },
              {
                id: 11143,
                name: "celery",
                localizedName: "celery",
                image: "celery.jpg",
              },
              {
                id: 11246,
                name: "leek",
                localizedName: "leek",
                image: "leeks.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Add broad beans and vegetable stock. Cover and simmer gently for 10 minutes, until the potatoes and broad beans are soft.",
            ingredients: [
              {
                id: 6615,
                name: "vegetable stock",
                localizedName: "vegetable stock",
                image: "chicken-broth.png",
              },
              {
                id: 16053,
                name: "fava beans",
                localizedName: "fava beans",
                image: "broad-beans.jpg",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Add parsley and salt  and pepper if needed.",
            ingredients: [
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
              {
                id: 1002030,
                name: "pepper",
                localizedName: "pepper",
                image: "pepper.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Serve with crusty bread.",
            ingredients: [
              {
                id: 10018029,
                name: "crusty bread",
                localizedName: "crusty bread",
                image: "crusty-bread.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 88.15331268310547,
    spoonacularSourceUrl: "https://spoonacular.com/monastery-soup-652332",
  },
  {
    id: 640575,
    image: "https://img.spoonacular.com/recipes/640575-556x370.png",
    imageType: "png",
    title: "Creamed Sweet Onion with Butter Basil Biscuits",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/MVQ4LBNM/creamed-sweet-onion-with-butter-basil-biscuits",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 16,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 2,
    healthScore: 1.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 133.86,
    extendedIngredients: [
      {
        id: 11294,
        aisle: "Produce",
        image: "sweet-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 Sweet Onion, halved and sliced",
        originalName: "Sweet Onion, halved and sliced",
        amount: 1.0,
        unit: "",
        meta: ["sweet", "halved", "sliced"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10123,
        aisle: "Meat",
        image: "raw-bacon.png",
        consistency: "SOLID",
        name: "bacon",
        nameClean: "bacon",
        original: "4 strips of bacon",
        originalName: "bacon",
        amount: 4.0,
        unit: "strips",
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "strips",
            unitLong: "strips",
          },
          metric: {
            amount: 4.0,
            unitShort: "strips",
            unitLong: "strips",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1 tbsp olive oil",
        originalName: "olive oil",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 1012049,
        aisle: "Produce",
        image: "thyme.jpg",
        consistency: "SOLID",
        name: "thyme",
        nameClean: "thyme",
        original: "2 sprigs of fresh thyme",
        originalName: "fresh thyme",
        amount: 2.0,
        unit: "sprigs",
        meta: ["fresh"],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "sprigs",
            unitLong: "sprigs",
          },
          metric: {
            amount: 2.0,
            unitShort: "sprigs",
            unitLong: "sprigs",
          },
        },
      },
      {
        id: 6194,
        aisle: "Canned and Jarred",
        image: "chicken-broth.png",
        consistency: "LIQUID",
        name: "chicken broth",
        nameClean: "chicken broth",
        original: "1 cup chicken broth",
        originalName: "chicken broth",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 235.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14106,
        aisle: "Alcoholic Beverages",
        image: "white-wine.jpg",
        consistency: "LIQUID",
        name: "white wine",
        nameClean: "white wine",
        original: "¼ cup white wine",
        originalName: "white wine",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 60.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "1 tbsp of butter",
        originalName: "butter",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "flour",
        original: "1 tbsp flour",
        originalName: "flour",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 1049,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "SOLID",
        name: "half and half",
        nameClean: "half and half",
        original: "¼ cup half and half",
        originalName: "half and half",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 60.5,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "Pinch of nutmeg",
        originalName: "Pinch of nutmeg",
        amount: 1.0,
        unit: "pinch",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "pinch",
            unitLong: "pinch",
          },
          metric: {
            amount: 1.0,
            unitShort: "pinch",
            unitLong: "pinch",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "Salt and pepper to taste",
        originalName: "Salt and pepper to taste",
        amount: 4.0,
        unit: "servings",
        meta: ["to taste"],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "all purpose flour",
        nameClean: "all purpose flour",
        original: "1 ¾ all purpose flour",
        originalName: "all purpose flour",
        amount: 1.75,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.75,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.75,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 18369,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "baking powder",
        nameClean: "baking powder",
        original: "1 tbsp baking powder",
        originalName: "baking powder",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "salt",
        original: "½ tsp salt",
        originalName: "salt",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 1145,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "6 tbsp unsalted butter, cubed",
        originalName: "unsalted butter, cubed",
        amount: 6.0,
        unit: "tbsp",
        meta: ["unsalted", "cubed"],
        measures: {
          us: {
            amount: 6.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 6.0,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 2044,
        aisle: "Produce",
        image: "fresh-basil.jpg",
        consistency: "SOLID",
        name: "basil",
        nameClean: "basil",
        original: "¼ cup fresh basil, chiffonade",
        originalName: "fresh basil, chiffonade",
        amount: 0.25,
        unit: "cup",
        meta: ["fresh"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 6.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1049,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "SOLID",
        name: "half and half",
        nameClean: "half and half",
        original: "¾ half and half",
        originalName: "half and half",
        amount: 0.75,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 0.75,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 0.75,
            unitShort: "",
            unitLong: "",
          },
        },
      },
    ],
    summary:
      'Creamed Sweet Onion with Butter Basil Biscuits might be just the hor d\'oeuvre you are searching for. This recipe serves 4 and costs $1.34 per serving. One serving contains <b>375 calories</b>, <b>5g of protein</b>, and <b>34g of fat</b>. This recipe from Foodista requires all purpose flour, bacon, white wine, and butter. 2 people found this recipe to be delicious and satisfying. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. With a spoonacular <b>score of 22%</b>, this dish is not so amazing. Try <a href="https://spoonacular.com/recipes/creamed-sweet-onion-with-butter-basil-biscuits-1369487">Creamed Sweet Onion with Butter Basil Biscuits</a>, <a href="https://spoonacular.com/recipes/warm-octopus-and-sweet-onion-salad-with-fresh-basil-and-lemon-vinaigrette-328022">Warm Octopus and Sweet Onion Salad with Fresh Basil and Lemon Vinaigrette</a>, and <a href="https://spoonacular.com/recipes/sweet-potato-biscuits-with-honey-butter-586112">Sweet Potato Biscuits with Honey Butter</a> for similar recipes.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: [],
    occasions: [],
    instructions:
      "Preheat oven to 450\nIn a heavy bottom pot fry bacon over medium heat until crispy.\nRemove from pot and leave to cool on a plate lined with paper towel.\nSpoon off the bacon grease leaving 2 tbsp worth in the pot.\nAdd the olive oil to keep the fat from burning and toss in the onions.\nSautee for 2-3 minutes.\nPour in broth and add the two sprigs of thyme.\nBring the mixture up to a boil and reduce heat and leave to simmer covered for 5 minutes.\nOnce onions are tender add white wine and leave to boil until the liquid is reduced by half.  About 10 minutes.\nIn a small saucepan melt butter over medium heat.\nWhisk in flour until it forms a paste.\nSlowly whisk in half and half until combined.  Remove from heat and add to the onion mixture. Stir until thickened.\nRemove from heat and set aside.\nSpoon into 4 ramenkins and top each with an uncooked biscuit.\nPlace in the oven and cook for 15 minutes until the biscuits are golden brown.\nRemove from the oven and leave to cool for ten minutes before serving.\nFOR THE BISCUITS\nSift together flour, baking powder, and salt into a large mixing bowl.\nAdd butter and basil.\nCut the butter into the dry mixture using a pastry blender or two knives until it resembles a coarse meal.\nMake a well in the center of the mixture and pour in the half and half.\nStir until the dough comes together.\nTurn dough onto a well-floured surface.\nFlatten dough to  an inch thickness.\nUsing a 2  biscuit cutter cut out 12 biscuits.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 450",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "In a heavy bottom pot fry bacon over medium heat until crispy.",
            ingredients: [
              {
                id: 10123,
                name: "bacon",
                localizedName: "bacon",
                image:
                  "https://spoonacular.com/cdn/ingredients_100x100/raw-bacon.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Remove from pot and leave to cool on a plate lined with paper towel.",
            ingredients: [],
            equipment: [
              {
                id: 405895,
                name: "paper towels",
                localizedName: "paper towels",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/paper-towels.jpg",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Spoon off the bacon grease leaving 2 tbsp worth in the pot.",
            ingredients: [
              {
                id: 4609,
                name: "bacon drippings",
                localizedName: "bacon drippings",
                image: "raw-bacon.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
              },
            ],
          },
          {
            number: 5,
            step: "Add the olive oil to keep the fat from burning and toss in the onions.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: "Sautee for 2-3 minutes.",
            ingredients: [],
            equipment: [],
            length: {
              number: 3,
              unit: "minutes",
            },
          },
          {
            number: 7,
            step: "Pour in broth and add the two sprigs of thyme.",
            ingredients: [
              {
                id: 1006615,
                name: "broth",
                localizedName: "broth",
                image: "chicken-broth.png",
              },
              {
                id: 2049,
                name: "thyme",
                localizedName: "thyme",
                image: "thyme.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Bring the mixture up to a boil and reduce heat and leave to simmer covered for 5 minutes.",
            ingredients: [],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 9,
            step: "Once onions are tender add white wine and leave to boil until the liquid is reduced by half.  About 10 minutes.",
            ingredients: [
              {
                id: 14106,
                name: "white wine",
                localizedName: "white wine",
                image: "white-wine.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 10,
            step: "In a small saucepan melt butter over medium heat.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/sauce-pan.jpg",
              },
            ],
          },
          {
            number: 11,
            step: "Whisk in flour until it forms a paste.",
            ingredients: [
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 12,
            step: "Slowly whisk in half and half until combined.",
            ingredients: [
              {
                id: 1049,
                name: "half and half",
                localizedName: "half and half",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 13,
            step: "Remove from heat and add to the onion mixture. Stir until thickened.",
            ingredients: [
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 14,
            step: "Remove from heat and set aside.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 15,
            step: "Spoon into 4 ramenkins and top each with an uncooked biscuit.",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 16,
            step: "Place in the oven and cook for 15 minutes until the biscuits are golden brown.",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              },
            ],
            length: {
              number: 15,
              unit: "minutes",
            },
          },
          {
            number: 17,
            step: "Remove from the oven and leave to cool for ten minutes before serving.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 18,
            step: "FOR THE BISCUITS",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 19,
            step: "Sift together flour, baking powder, and salt into a large mixing bowl.",
            ingredients: [
              {
                id: 18369,
                name: "baking powder",
                localizedName: "baking powder",
                image: "white-powder.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 405907,
                name: "mixing bowl",
                localizedName: "mixing bowl",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/mixing-bowl.jpg",
              },
            ],
          },
          {
            number: 20,
            step: "Add butter and basil.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 2044,
                name: "basil",
                localizedName: "basil",
                image: "basil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 21,
            step: "Cut the butter into the dry mixture using a pastry blender or two knives until it resembles a coarse meal.",
            ingredients: [
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
            ],
            equipment: [
              {
                id: 404726,
                name: "blender",
                localizedName: "blender",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/blender.png",
              },
            ],
          },
          {
            number: 22,
            step: "Make a well in the center of the mixture and pour in the half and half.",
            ingredients: [
              {
                id: 1049,
                name: "half and half",
                localizedName: "half and half",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 23,
            step: "Stir until the dough comes together.",
            ingredients: [
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 24,
            step: "Turn dough onto a well-floured surface.",
            ingredients: [
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 25,
            step: "Flatten dough to  an inch thickness.",
            ingredients: [
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
            ],
            equipment: [],
          },
          {
            number: 26,
            step: "Using a 2  biscuit cutter cut out 12 biscuits.",
            ingredients: [
              {
                id: 18009,
                name: "biscuits",
                localizedName: "biscuits",
                image: "buttermilk-biscuits.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 28.46582794189453,
    spoonacularSourceUrl:
      "https://spoonacular.com/creamed-sweet-onion-with-butter-basil-biscuits-640575",
  },
  {
    id: 637016,
    image: "https://img.spoonacular.com/recipes/637016-556x370.jpg",
    imageType: "jpg",
    title: "Caramel Peanut Fudge Cake",
    readyInMinutes: 45,
    servings: 10,
    sourceUrl: "https://www.foodista.com/recipe/DFQVM7MF/caramel-peanut-cake",
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 18,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 84,
    healthScore: 21.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 124.28,
    extendedIngredients: [
      {
        id: 12061,
        aisle: "Nuts",
        image: "almonds.jpg",
        consistency: "SOLID",
        name: "almonds",
        nameClean: "almonds",
        original: "100g almonds, finely ground",
        originalName: "almonds, finely ground",
        amount: 100.0,
        unit: "g",
        meta: ["finely"],
        measures: {
          us: {
            amount: 3.527,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 100.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 19165,
        aisle: "Baking",
        image: "cocoa-powder.png",
        consistency: "SOLID",
        name: "cocoa",
        nameClean: "cocoa",
        original: "25g cocoa",
        originalName: "cocoa",
        amount: 25.0,
        unit: "g",
        meta: [],
        measures: {
          us: {
            amount: 0.882,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 25.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 19165,
        aisle: "Baking",
        image: "cocoa-powder.png",
        consistency: "SOLID",
        name: "chocolate of at least cocoa parts",
        nameClean: "chocolate of at least cocoa parts",
        original: "300g chocolate of at least 70% cocoa parts",
        originalName: "chocolate of at least 70% cocoa parts",
        amount: 300.0,
        unit: "g",
        meta: ["70%"],
        measures: {
          us: {
            amount: 10.582,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 300.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1053,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "LIQUID",
        name: "cream",
        nameClean: "cream",
        original: "500ml cream",
        originalName: "cream",
        amount: 500.0,
        unit: "ml",
        meta: [],
        measures: {
          us: {
            amount: 2.113,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 500.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1124,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg-white.jpg",
        consistency: "SOLID",
        name: "eggs",
        nameClean: "eggs",
        original: "6 eggs, egg yolks separated from the egg whites",
        originalName: "eggs, egg yolks separated from the egg whites",
        amount: 6.0,
        unit: "",
        meta: ["separated"],
        measures: {
          us: {
            amount: 6.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 6.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 16091,
        aisle: "Savory Snacks",
        image: "peanuts.png",
        consistency: "SOLID",
        name: "peanuts",
        nameClean: "peanuts",
        original: "150g peanuts, coarsely chopped",
        originalName: "peanuts, coarsely chopped",
        amount: 150.0,
        unit: "g",
        meta: ["coarsely chopped"],
        measures: {
          us: {
            amount: 5.291,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 150.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 11114037,
        aisle: "Alcoholic Beverages",
        image: "rum-dark.jpg",
        consistency: "LIQUID",
        name: "rum",
        nameClean: "rum",
        original: "1 Tbs rum",
        originalName: "rum",
        amount: 1.0,
        unit: "Tbs",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbs",
            unitLong: "Tb",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbs",
            unitLong: "Tb",
          },
        },
      },
      {
        id: 19335,
        aisle: "Baking",
        image: "sugar-in-bowl.png",
        consistency: "SOLID",
        name: "sugar",
        nameClean: "sugar",
        original: "150g sugar",
        originalName: "sugar",
        amount: 150.0,
        unit: "g",
        meta: [],
        measures: {
          us: {
            amount: 5.291,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 150.0,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "2 Tbs water",
        originalName: "water",
        amount: 2.0,
        unit: "Tbs",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
          metric: {
            amount: 2.0,
            unitShort: "Tbs",
            unitLong: "Tbs",
          },
        },
      },
    ],
    summary:
      'Caramel Peanut Fudge Cake might be just the dessert you are searching for. One portion of this dish contains approximately <b>16g of protein</b>, <b>35g of fat</b>, and a total of <b>459 calories</b>. This recipe serves 10. For <b>$1.24 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes about <b>45 minutes</b>. 84 people were glad they tried this recipe. If you have almonds, sugar, cream, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. It is a good option if you\'re following a <b>gluten free and lacto ovo vegetarian</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 74%</b>, which is solid. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/slow-cooker-caramel-peanut-butter-hot-fudge-cake-1331813">Slow Cooker Caramel Peanut Butter Hot Fudge Cake</a>, <a href="https://spoonacular.com/recipes/slow-cooker-caramel-peanut-butter-hot-fudge-cake-951248">Slow Cooker Caramel Peanut Butter Hot Fudge Cake</a>, and <a href="https://spoonacular.com/recipes/caramel-peanut-butter-fudge-573829">Caramel Peanut Butter Fudge</a>.',
    cuisines: [],
    dishTypes: ["dessert"],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: [],
    instructions:
      "<ol><li>For the sponge, beat egg yolks with sugar for 3-4 minutes until the mixture doubles in volume and becomes pale yellow.</li><li>Whisk the egg whites until soft peaks form.</li><li>Fold the egg whites gently into the egg yolks cream.</li><li>Gently stir in almonds and cocoa.</li><li>Lightly butter and flour a 20 round cake pan, line with parchment paper. Pour in the sponge mixture Bake in preheated oven at 180C for about 20 minutes or until done (the trick with a toothpick).</li><li>Leave the cake to cool completely in the cake pan, then carefully remove it and split into two layers.</li><li>For the caramel cream heat sugar and water over medium heat and cook, stirring occasionally, until the sugar dissolves and comes to a boil. Continue cooking, but without stirring, until mixture becomes golden amber in color. Remove from flame and set aside.</li><li>Whip the cream, gradually stir in the caramel syrup.</li><li>Add peanuts, stir and combine. Mixture must be smooth (at first it will foam up a little). Transfer the cream to a bowl to cool down to room temperature and thicken.</li><li>For the ganache bring the cream just to a boil over medium-high heat; pour over chocolate. Let stand 10 minutes. Stir very gently for 3-4 minutes until smooth and glossy, incorporating the cream steadily, without overworking.</li><li>Cool ganache for an hour or until completely chilled, then beat for 2-3 minutes or until it becomes fluffy and lighter in color. Do not overbeat because it will become too thick and not spreadable.</li><li>To assemble the cake, first sprinkle each cake layer with half of the rum and water syrup.</li><li>Spread the caramel cream over the bottom layer, cover with the top layer (wet side down).</li><li>Immediately spread ganache over top and sides of cake.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "For the sponge, beat egg yolks with sugar for 3-4 minutes until the mixture doubles in volume and becomes pale yellow.",
            ingredients: [
              {
                id: 1125,
                name: "egg yolk",
                localizedName: "egg yolk",
                image: "egg-yolk.jpg",
              },
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
            ],
            equipment: [],
            length: {
              number: 4,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Whisk the egg whites until soft peaks form.Fold the egg whites gently into the egg yolks cream.Gently stir in almonds and cocoa.Lightly butter and flour a 20 round cake pan, line with parchment paper.",
            ingredients: [
              {
                id: 1124,
                name: "egg whites",
                localizedName: "egg whites",
                image: "egg-white.jpg",
              },
              {
                id: 1125,
                name: "egg yolk",
                localizedName: "egg yolk",
                image: "egg-yolk.jpg",
              },
              {
                id: 12061,
                name: "almonds",
                localizedName: "almonds",
                image: "almonds.jpg",
              },
              {
                id: 1001,
                name: "butter",
                localizedName: "butter",
                image: "butter-sliced.jpg",
              },
              {
                id: 19165,
                name: "cocoa powder",
                localizedName: "cocoa powder",
                image: "cocoa-powder.png",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
            ],
            equipment: [
              {
                id: 404770,
                name: "baking paper",
                localizedName: "baking paper",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/baking-paper.jpg",
              },
              {
                id: 404747,
                name: "cake form",
                localizedName: "cake form",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/cake-pan.png",
              },
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 3,
            step: "Pour in the sponge mixture",
            ingredients: [],
            equipment: [],
          },
          {
            number: 4,
            step: "Bake in preheated oven at 180C for about 20 minutes or until done (the trick with a toothpick).Leave the cake to cool completely in the cake pan, then carefully remove it and split into two layers.For the caramel cream heat sugar and water over medium heat and cook, stirring occasionally, until the sugar dissolves and comes to a boil. Continue cooking, but without stirring, until mixture becomes golden amber in color.",
            ingredients: [
              {
                id: 19074,
                name: "caramel",
                localizedName: "caramel",
                image:
                  "https://spoonacular.com/cdn/ingredients_100x100/soft-caramels.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [
              {
                id: 404644,
                name: "toothpicks",
                localizedName: "toothpicks",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/toothpicks.jpg",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                temperature: {
                  number: 180.0,
                  unit: "Celsius",
                },
              },
              {
                id: 404747,
                name: "cake form",
                localizedName: "cake form",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/cake-pan.png",
              },
            ],
            length: {
              number: 20,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Remove from flame and set aside.Whip the cream, gradually stir in the caramel syrup.",
            ingredients: [
              {
                id: 19364,
                name: "caramel sauce",
                localizedName: "caramel sauce",
                image: "caramel-sauce.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: "Add peanuts, stir and combine.",
            ingredients: [
              {
                id: 16091,
                name: "peanuts",
                localizedName: "peanuts",
                image: "peanuts.png",
              },
            ],
            equipment: [],
          },
          {
            number: 7,
            step: "Mixture must be smooth (at first it will foam up a little).",
            ingredients: [],
            equipment: [],
          },
          {
            number: 8,
            step: "Transfer the cream to a bowl to cool down to room temperature and thicken.For the ganache bring the cream just to a boil over medium-high heat; pour over chocolate.",
            ingredients: [
              {
                id: 19081,
                name: "chocolate",
                localizedName: "chocolate",
                image: "milk-chocolate.jpg",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
              },
            ],
          },
          {
            number: 9,
            step: "Let stand 10 minutes. Stir very gently for 3-4 minutes until smooth and glossy, incorporating the cream steadily, without overworking.Cool ganache for an hour or until completely chilled, then beat for 2-3 minutes or until it becomes fluffy and lighter in color. Do not overbeat because it will become too thick and not spreadable.To assemble the cake, first sprinkle each cake layer with half of the rum and water syrup.",
            ingredients: [
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 0,
                name: "syrup",
                localizedName: "syrup",
                image: "",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 11114037,
                name: "rum",
                localizedName: "rum",
                image: "rum-dark.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 17,
              unit: "minutes",
            },
          },
          {
            number: 10,
            step: "Spread the caramel cream over the bottom layer, cover with the top layer (wet side down).Immediately spread ganache over top and sides of cake.",
            ingredients: [
              {
                id: 19074,
                name: "caramel",
                localizedName: "caramel",
                image:
                  "https://spoonacular.com/cdn/ingredients_100x100/soft-caramels.jpg",
              },
              {
                id: 0,
                name: "spread",
                localizedName: "spread",
                image: "",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 85.94318389892578,
    spoonacularSourceUrl:
      "https://spoonacular.com/caramel-peanut-fudge-cake-637016",
  },
  {
    id: 716412,
    image: "https://img.spoonacular.com/recipes/716412-556x370.jpg",
    imageType: "jpg",
    title: "Roasted Cranberries, Ricotta & Honey Crostini",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2013/12/roasted-cranberries-ricotta-honey.html",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 548,
    healthScore: 2.0,
    creditsText: "Full Belly Sisters",
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    pricePerServing: 147.74,
    extendedIngredients: [
      {
        id: 18064,
        aisle: "Bakery/Bread",
        image: "white-bread.jpg",
        consistency: "SOLID",
        name: "peasant bread",
        nameClean: "peasant bread",
        original: "slice of peasant bread",
        originalName: "peasant bread",
        amount: 1.0,
        unit: "slice",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "slice",
            unitLong: "slice",
          },
          metric: {
            amount: 1.0,
            unitShort: "slice",
            unitLong: "slice",
          },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "SOLID",
        name: "fresh-ground pepper",
        nameClean: "fresh-ground pepper",
        original: "fresh-ground pepper",
        originalName: "fresh-ground pepper",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 19296,
        aisle: "Nut butters, Jams, and Honey",
        image: "honey.png",
        consistency: "LIQUID",
        name: "honey",
        nameClean: "honey",
        original: "honey",
        originalName: "honey",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 1036,
        aisle: "Cheese",
        image: "ricotta.png",
        consistency: "SOLID",
        name: "ricotta",
        nameClean: "ricotta",
        original: "ricotta",
        originalName: "ricotta",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 1159,
        aisle: "Cheese",
        image: "goat-cheese.jpg",
        consistency: "SOLID",
        name: "ricotta",
        nameClean: "ricotta",
        original:
          "ricotta (try my easy, creamy homemade ricotta! or goat cheese would be work wonderfully, too)",
        originalName:
          "ricotta (try my easy, creamy homemade ricotta! or goat cheese would be work wonderfully, too)",
        amount: 1.0,
        unit: "serving",
        meta: [
          "homemade",
          "(try my easy, creamy ricotta! or goat cheese would be work wonderfully, too)",
        ],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 1012047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "sea salt",
        nameClean: "sea salt",
        original: "sea salt",
        originalName: "sea salt",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 9081,
        aisle: "Canned and Jarred",
        image: "cranberry-sauce.jpg",
        consistency: "SOLID",
        name: "roasted cranberry sauce",
        nameClean: "roasted cranberry sauce",
        original: "roasted cranberry sauce",
        originalName: "roasted cranberry sauce",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1.0,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
    ],
    summary:
      'You can never have too many Mediterranean recipes, so give Roasted Cranberries, Ricotta & Honey Crostini a try. One portion of this dish contains about <b>9g of protein</b>, <b>8g of fat</b>, and a total of <b>290 calories</b>. For <b>$1.48 per serving</b>, this recipe <b>covers 7%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. It works well as an affordable hor d\'oeuvre for <b>Christmas</b>. It is brought to you by fullbellysisters.blogspot.com. 548 people were glad they tried this recipe. If you have peasant bread, ricotta, roasted cranberry sauce, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>rather bad spoonacular score of 28%</b>. <a href="https://spoonacular.com/recipes/roasted-fig-ricotta-pistachio-honey-crostini-721464">Roasted Fig, Ricotta, Pistachio & Honey Crostini</a>, <a href="https://spoonacular.com/recipes/maple-honey-roasted-carrot-noodle-ricotta-crostini-with-coconut-flakes-563844">Maple-Honey Roasted Carrot Noodle Ricotta Crostini with Coconut Flakes</a>, and <a href="https://spoonacular.com/recipes/honey-chipotle-roasted-parsnip-and-carrot-crostini-with-whipped-ricotta-and-pesto-619399">Honey Chipotle-Roasted Parsnip and Carrot Crostini with Whipped Ricottan and Pesto</a> are very similar to this recipe.',
    cuisines: ["Mediterranean", "Italian", "European"],
    dishTypes: [
      "fingerfood",
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: [],
    occasions: ["christmas"],
    instructions: "",
    analyzedInstructions: [],
    originalId: null,
    spoonacularScore: 19.95264434814453,
    spoonacularSourceUrl:
      "https://spoonacular.com/roasted-cranberries-ricotta-honey-crostini-716412",
  },
];

// For extended Ingredients use "original" tag? (example: "        original: "1 onion, chopped",
// ")
